// Generates src/version.ts from package.json so the CLI does not need to
// read package.json at runtime. Run by the `gen:version` script before tsc.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));
const out = `// Auto-generated by scripts/gen-version.mjs. Do not edit.\nexport const PKG_VERSION = '${pkg.version}';\n`;
writeFileSync(resolve(root, 'src', 'version.ts'), out, 'utf8');
